
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int STRING_LITERAL = 12;
  public static final int MULT = 28;
  public static final int CHAR = 4;
  public static final int CHAR_LITERAL = 11;
  public static final int ABRE_CHAVE = 32;
  public static final int CASE = 17;
  public static final int DIFERENTE = 21;
  public static final int FECHA_CHAVE = 33;
  public static final int ABRE_PAREN = 30;
  public static final int NUM_INT = 9;
  public static final int INT = 2;
  public static final int FECHA_PAREN = 31;
  public static final int FOR = 36;
  public static final int DOIS_PONTOS = 34;
  public static final int IDENTIFICADOR = 8;
  public static final int IGUAL = 5;
  public static final int VIRG = 7;
  public static final int MAIS = 26;
  public static final int DIV = 29;
  public static final int IF = 14;
  public static final int PVIRG = 6;
  public static final int IGUAL_IGUAL = 20;
  public static final int EOF = 0;
  public static final int MAIOR = 23;
  public static final int error = 1;
  public static final int MENOS = 27;
  public static final int MENOR = 22;
  public static final int BREAK = 19;
  public static final int ERROR = 13;
  public static final int SWITCH = 16;
  public static final int NUM_REAL = 10;
  public static final int ELSE = 15;
  public static final int WHILE = 35;
  public static final int DEFAULT = 18;
  public static final int FLOAT = 3;
  public static final int MENOR_IGUAL = 24;
  public static final int MAIOR_IGUAL = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "CHAR",
  "IGUAL",
  "PVIRG",
  "VIRG",
  "IDENTIFICADOR",
  "NUM_INT",
  "NUM_REAL",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "ERROR",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAIOR",
  "MENOR_IGUAL",
  "MAIOR_IGUAL",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "ABRE_PAREN",
  "FECHA_PAREN",
  "ABRE_CHAVE",
  "FECHA_CHAVE",
  "DOIS_PONTOS",
  "WHILE",
  "FOR"
  };
}

